server:
  port: 9090
  ssl:
    enabled: true
    key-store: classpath:ssl.jks
    key-store-password: 19990711Aa
    key-store-type: JKS
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://49.235.127.31:3306/facetocode?useunicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
#    url: jdbc:mysql://42.192.224.189:3306/facetocode?useunicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false
    username: facetocode
    password: "002582"
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 6379
    host: 49.235.127.31
    #    host: 42.192.224.189
#    password: 112233
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0ms
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  mail:
    host: smtp.qq.com
    username: 1743394547@qq.com
    password: nbfozazeuiitecji
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
    ##         ssl:
    ##           enable :true
    default-encoding: utf-8
# MyBatis-配置
mybatis-plus:
  # xml
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package:
  global-config:
    # banner打印
    banner: true
  configuration:
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    # 开启驼峰命名
    map-underscore-to-camel-case: false
    # SQL输出日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

knife4j:
#  production: false
  basic:
    enable: true
    username: root
    password: root
  enable: false
